### ISSUE TITLE
Detected Native memory leak or slow reclamation of native memory

### ISSUE THREAD

**Issue by alee-r7** [luben/zstd-jni#156] opened 2021-01-19 21:21 UTC
Hello, we started to use zstd using Zstd.decompress, compress and the ZstdOutputStream. We use these calls method numerous times over a jvm process's lifetime which is long running. We started to now run into issues were the process itself is consuming nearly all of the host's memory going well beyond the jvm's -mx value. When it crashes there is no heap dump. Non heap seems ok, so it looks like its pointing to jni stuff. The only jni our application uses is the zstd stuff. Anyhow, I believe I traced the issue down into the this test driver below

```
byte[] array = new byte[100];
    new Random().nextBytes(array);
    Path tempPath = Files.createTempFile("test", "test");
    for (int i = 0; i < 10000000; i++) {
      try (ZstdOutputStream zstdOutput = new ZstdOutputStream(new FileOutputStream(tempPath.toFile()));
           InputStream inputStream = new StringInputStream(new String(array, Charset.forName("UTF-8")))) {
        ByteStreams.copy(inputStream, zstdOutput);
        System.out.println("TEST");
        System.gc();
      } finally {
        Files.deleteIfExists(tempPath);
      }
    }
    System.out.println("Done!!!!");
```
Notice the System.gc, when I comment that line out..the program itself consumes about 8GB with very little heap consumed. If I leave the System.gc the program barely consumes any memory.

Is this something I have to code against or bug against ZstdOutputStream. I'm assumed the auto-close will free up the native resources, but perhaps I'm not understanding a certain aspect with native resources and how it finalizes and when the GC decides to collect it.

**Comment by luben** [comment] 2021-01-20 23:18
Hmm, that's interesting. I have not looked closely at the semantics of the auto-close. I don't think we support it due to supporting Java 6 that lacks this interface. Can you try something for me - replace the `System.gc()` with `zstdOutput.close()`: does it still goes OOM?

May be it's time to drop Java 6 support - it will allow to simplify some code internally also.

**Comment by alee-r7** [comment] 2021-01-21 00:04
Hi, it still has the issue. I took out the auto close and manually called closed and commented out the System.gc. I'm not sure if its the version of java I'm using. I running it on openjdk 11 and zulu version of 11. I'll try java 8 and see if it changes anything.

**Comment by luben** [comment] 2021-01-21 14:02
Hi,

First, my assumption about the auto-close was wrong - it should work as the abstract class that `ZstdOutputStream` extends (`FilterOutputStream`) implements it.

I compiled the example (with small modifications: https://gist.github.com/luben/0b0e21feb8f359a0b36a74977f1b4f9a) and run it locally with JDK-11 (OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)) and few GC configs for 10 million iterations each. Here is example how I run it:
```
/usr/local/jdk-11/bin/java -cp . -Xms1024m -Xmx1024m -XX:+UnlockExperimentalVMOptions -XX:+AlwaysPreTouch -XX:+UseG1GC com.github.luben.zstd.TestLeak
```
-XX:+UseParallelGC:  settles on 1097 MB RSS
-XX:+UseG1GC: settles on 1113 MB
-XX:+UseShenandoahGC: settles on  1091 MB
-XX:+UseZGC: starts at 3051 MB  and grows very slowly ???

I also tried with bigger heap - 4GB  and all of them, except ZGC settle at 4200-4306 MB. ZGC grows to 12367 MB so yes there is something that may depend on how frequently the GC is running. But also there seems to be an issue with ZGC.

What GC did you use in your experiments?

**Comment by alee-r7** [comment] 2021-01-21 21:40
Thanks, so I found some interesting observations. My experiment was 8GB heap. On my laptop its using openjdk 11.

I used your settings and i found this from looking a jvm process mem usage.

-XX:+UseParallelGC: Settled down about 4-5 GB of usage.
-XX:+UseG1GC: Settled down to about 8 GB of mem usage.
-XX:+UseZGC: Settled down to about 6 GB of usage.

The code itself should take up very little memory, only when the System.gc is called does it stay near zero by just looking at htop. Now in terms of heap usage, I noticed spikes up and down in the range of 2GB to 6GB the parrallel gc seemed to be stabilize at 2.5GB but survivor space was near full.  Now for the way we want to use zstd is to have 1 jvm calling the zstd library multiple times over many concurrent threads talking 100-200 threads at the same time. So perhaps its simply the JVM is not fast enough to clean up. This call in G1GC seems to clean it the native code.
```
[2.388s][info   ][gc,task        ] GC(220) Using 1 workers of 8 for full compaction
[2.388s][info   ][gc,start       ] GC(220) Pause Full (System.gc())
[2.388s][info   ][gc,phases,start] GC(220) Phase 1: Mark live objects
[2.391s][info   ][gc,stringtable ] GC(220) Cleaned string and symbol table, strings: 3913 processed, 0 removed, symbols: 35631 processed, 0 removed
[2.391s][info   ][gc,phases      ] GC(220) Phase 1: Mark live objects 2.731ms
[2.391s][info   ][gc,phases,start] GC(220) Phase 2: Prepare for compaction
[2.392s][info   ][gc,phases      ] GC(220) Phase 2: Prepare for compaction 1.040ms
[2.392s][info   ][gc,phases,start] GC(220) Phase 3: Adjust pointers
[2.393s][info   ][gc,phases      ] GC(220) Phase 3: Adjust pointers 1.069ms
[2.393s][info   ][gc,phases,start] GC(220) Phase 4: Compact heap
[2.393s][info   ][gc,phases      ] GC(220) Phase 4: Compact heap 0.297ms
[2.394s][info   ][gc,heap        ] GC(220) Eden regions: 1->0(4)
[2.394s][info   ][gc,heap        ] GC(220) Survivor regions: 0->0(0)
[2.394s][info   ][gc,heap        ] GC(220) Old regions: 3->3
[2.394s][info   ][gc,heap        ] GC(220) Humongous regions: 1->1
[2.394s][info   ][gc,metaspace   ] GC(220) Metaspace: 9299K->9299K(1058816K)
[2.394s][info   ][gc             ] GC(220) Pause Full (System.gc()) 7M->7M(28M) 5.523ms
[2.394s][info   ][gc,cpu         ] GC(220) User=0.00s Sys=0.00s Real=0.00s
```
without system.gc you get these a lot. 

```
[2.690s][info   ][gc,start      ] GC(13) Pause Young (Concurrent Start) (G1 Evacuation Pause)
[2.690s][info   ][gc,task       ] GC(13) Using 8 workers of 8 for evacuation
[2.722s][info   ][gc,phases     ] GC(13)   Pre Evacuate Collection Set: 0.0ms
[2.722s][info   ][gc,phases     ] GC(13)   Evacuate Collection Set: 0.4ms
[2.722s][info   ][gc,phases     ] GC(13)   Post Evacuate Collection Set: 31.4ms
[2.722s][info   ][gc,phases     ] GC(13)   Other: 0.3ms
[2.722s][info   ][gc,heap       ] GC(13) Eden regions: 76->0(119)
[2.722s][info   ][gc,heap       ] GC(13) Survivor regions: 82->20(20)
[2.722s][info   ][gc,heap       ] GC(13) Old regions: 927->981
[2.722s][info   ][gc,heap       ] GC(13) Humongous regions: 1->1
[2.722s][info   ][gc,metaspace  ] GC(13) Metaspace: 9377K->9377K(1058816K)
[2.722s][info   ][gc            ] GC(13) Pause Young (Concurrent Start) (G1 Evacuation Pause) 2171M->2002M(5170M) 32.229ms
[2.722s][info   ][gc,cpu        ] GC(13) User=0.17s Sys=0.01s Real=0.03s
[2.723s][info   ][gc            ] GC(14) Concurrent Cycle
[2.723s][info   ][gc,marking    ] GC(14) Concurrent Clear Claimed Marks
[2.723s][info   ][gc,marking    ] GC(14) Concurrent Clear Claimed Marks 0.005ms
[2.723s][info   ][gc,marking    ] GC(14) Concurrent Scan Root Regions
[2.723s][info   ][gc,marking    ] GC(14) Concurrent Scan Root Regions 0.441ms
[2.723s][info   ][gc,marking    ] GC(14) Concurrent Mark (2.723s)
[2.723s][info   ][gc,marking    ] GC(14) Concurrent Mark From Roots
[2.723s][info   ][gc,task       ] GC(14) Using 2 workers of 2 for marking
[2.728s][info   ][gc,marking    ] GC(14) Concurrent Mark From Roots 4.777ms
[2.728s][info   ][gc,marking    ] GC(14) Concurrent Preclean
[2.728s][info   ][gc,marking    ] GC(14) Concurrent Preclean 0.059ms
[2.728s][info   ][gc,marking    ] GC(14) Concurrent Mark (2.723s, 2.728s) 4.848ms
[2.728s][info   ][gc,start      ] GC(14) Pause Remark
[2.729s][info   ][gc,stringtable] GC(14) Cleaned string and symbol table, strings: 3981 processed, 0 removed, symbols: 35631 processed, 0 removed
[2.730s][info   ][gc            ] GC(14) Pause Remark 2008M->182M(5170M) 2.187ms
[2.730s][info   ][gc,cpu        ] GC(14) User=0.01s Sys=0.01s Real=0.00s
[2.730s][info   ][gc,marking    ] GC(14) Concurrent Rebuild Remembered Sets
[2.731s][info   ][gc,marking    ] GC(14) Concurrent Rebuild Remembered Sets 1.113ms
[2.731s][info   ][gc,start      ] GC(14) Pause Cleanup
[2.731s][info   ][gc            ] GC(14) Pause Cleanup 184M->184M(5170M) 0.246ms
[2.731s][info   ][gc,cpu        ] GC(14) User=0.00s Sys=0.00s Real=0.00s
[2.731s][info   ][gc,marking    ] GC(14) Concurrent Cleanup for Next Mark
```

**Comment by luben** [comment] 2021-01-21 22:30
Hmm, I see. There are two distinct memory allocations:

- native memory used by the library, allocated through the system allocator. It is cleaned on `close` and it will grow linearly with the number if instances of Zstd(Input|Output)Streams you have alive. Memory is reclaimed immediately, though the system allocator may not return it straight away to the OS.
- Java heap memory - there is also a buffer allocated in the java part of the code. It is cleaned through the GC. The figures you show totally make sense - all GC will try to minimize the pauses so they try to GC as rarely as possible. This means they will prefer allocating until the there is no free space (or close). The difference between GC algorithms used is caused by different heuristics for promotion to old-gen and how each of them moves the boundary between old and new gen. This test is new-gen heavy as we don't hold on any memory for a long. I am a little but surprised that the survivor space is used at all.

So here are a few things we can make to reduce the pressure on the Java heap/GC:
- if the size of the files you want to compress is pre-determined and not quite big, you can read the file, compress it in one go using `ZstdCompressCtx` and later reuse the context object. Though in this case you have to manually pool you input/output buffers.
- I have recently added an option to give a buffer supplier to the stream classes. By default it uses noop supplier that does not cache the buffers, but there is also a buffer pool that reuses the buffers: look for the constructor that takes BufferPool and pass it RecyclingBufferPool.INSTANCE  (https://www.javadoc.io/doc/com.github.luben/zstd-jni/latest/com/github/luben/zstd/RecyclingBufferPool.html). Try it, it may solve your case but it's not silver bullet.
- If you already have out input/outputs as direct `ByteBuffer`s there  is an option to use `ZstdDirectBufferCompressingStream` with your buffer management strategy. This will not allocate any Java heap but it's more involved as you have to manage the buffers yourself and also does not implement the Stream interfaces. There are a test how to use it, e.g. https://github.com/luben/zstd-jni/blob/master/src/test/scala/Perf.scala#L241-L284

I hope this helps

**Comment by luben** [comment] 2021-01-21 22:33
Just a note about your GC logs with G1GC: it tries to minimize pauses and splits the heap in multiple regions. On each iteration it GCs only a few regions, that's why you don't see it drop to 0 (or close).

**Comment by luben** [comment] 2021-01-21 23:09
I updated the https://gist.github.com/luben/0b0e21feb8f359a0b36a74977f1b4f9a with the suggested buffer pool strategy, and also using static buffer for the copy. It does not GC compared to previous version. There are still few GC cycles due to InputStream and OutputStream being allocated per loop cycle.

**Comment by alee-r7** [comment] 2021-01-22 21:19
So I just tried your buffer pool and it works great on my test run, seems like the silver bullet solution to me. It hardly goes up, (using G1GC). I'll try this out in our production scenario, but would there be any concern in terms of concurrency. I'm assuming underneath it works similar to like a thread pool? So most likely I'd see a bump in the memory still but it should settle at a much lower range. I'll let you know how it works out.

**Comment by luben** [comment] 2021-01-22 21:52
Yes, that is the expected behaviour. Internally it uses soft references that can be collected under memory pressure. It may cause some issues with some garbage collectors, though jvm-11 have solved most of them.

Curious to hear back your experience putting it in production.

**Comment by alee-r7** [comment] 2021-01-23 16:20
So after running it in production for almost a day here are my observations.

1. My instances are stable now where it doesn't crash because of memory error.
2. I've allocated 30 GB ec2s and my application over time goes up and settles areund 24-26 GB of used memory.
3. The heap is set to a max of 21 GB via a percentage but actual used heap is in the range of 4-12 GB
4. I call system.gc once an hour but I think this has little effect now due to the soft references.

My instances process things really fast at the beginning then slow down and stabilizes which isn't slow but isn't as fast as when the first 2-3 hours. 

I took a closer look at the pool, and I'm thinking to make this work even better I could try a timed pool approach where I replace the internal map of RecyclingBuffer and replace it with something like Guava cache. I'm thinking having a expiration if it wasn't used in the last hour to purge it from the cache that and the combo of maybe hourly System.gc may work well for my deployment.  I'lll let you know how that goes.

**Comment by luben** [comment] 2021-01-23 16:31
Yes, have less "naive" buffer pool should improve performance. You can implement it in your app and pass an instance to `ZstdOuputStream`. I plan to put some improvements in the buffer pool:
- allocate only buffers of sizes that are power of 2. Then instead if having a hash-map, use an array and index by the power of 2.
- may be keep some stats and trim unused buffers, as you proposed

**Comment by alee-r7** [comment] 2021-01-24 16:26
Further testing and observation and discovered that the hashmap at least on my deployments only has a size of 1 the whole time. It looks like the capacity value if fixed and is determined by the native call for recommended capacity (I forgot what that value is). The dequeue portion is the part that grows and doesn't go back down. I've seen it a high as 83 just doing some sampling. Anyhow sorta had my own implementation of the pool using a combo of guava cache to replace the hashmap and the apache commons pool to replace the dequeue. So far it hasn't really given any boosts in performance. If i set the pool to low, the pool will destroy the bytebuffers too quickly, which causes a spike in memory. So I find myself bumping it up from max idle of 20 to like 50 which seemed to bring it back on par with the original implementation. Leads me to believe, perhaps given my application load I will need many buffers and the increase in memory is just a requirements for now.  Will keep playing around to see what else can be done.

**Comment by luben** [comment] 2021-01-24 16:57
Yes, I also think the hash-map in the implementation is not needed.

**Comment by luben** [comment] 2021-01-29 08:22
Closing for now. In the future I may look how to simplify the buffer pool.

**Closed by luben** 2021-01-29 08:22 UTC
